language: java
dist: xenial
jdk:
    - openjdk11
install: true
cache:
  directories:
    - $HOME/.m2/repository
env:
  global:
    - MAVEN_OPTS="-Xmx1024M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
    - _JAVA_OPTIONS="-Djdk.net.URLClassPath.disableClassPathURLCheck=true -Xmx2048m -Xms512m"
script:
  - mvn -B clean install && mvn -B javadoc:javadoc
after_script:
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DfailOnMissingReportFile=false
