language: java
dist: bionic
jdk:
    - openjdk12

addons:
  apt:
    packages:
      - oracle-java12-installer
install: true
cache:
  directories:
    - $HOME/.m2/repository
env:
  global:
    - JAVA_HOME=/usr/local/lib/jvm/openjdk11
    - MAVEN_OPTS="-Xmx1024M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
    - _JAVA_OPTIONS="-Djdk.net.URLClassPath.disableClassPathURLCheck=true -Xmx2048m -Xms512m"
script:
  - echo $JAVA_HOME
  - mvn -t .travis-toolchains.xml -B clean install javadoc:javadoc
after_script:
  - mvn -t .travis-toolchains.xml com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DfailOnMissingReportFile=false
