name: Java CI

on: [ push, pull_request ]

env:
  MAVEN_OPTS: -Xmx1024M -Xss128M -XX:+CMSClassUnloadingEnabled

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: adopt

    - name: Restore Maven cache
      uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore

    - name: Build
      run: mvn --batch-mode --update-snapshots verify javadoc:javadoc

    - name: Save Maven cache
      uses: skjolber/maven-cache-github-action@v1
      with:
        step: save
